export const ROLES_SERVICES = 'ROLES_SERVICES';
export const TEAMS_SERVICES = 'TEAMS_SERVICES';
export const USERS_SERVICES = 'USERS_SERVICES';
export const PROJECTS_SERVICES = 'PROJECTS_SERVICES';
export const PROJECTS_X_USERS_SERVICES = 'PROJECTS_X_USERS_SERVICES';
export const STATUS_TASKS_SERVICES = 'STATUS_TASKS_SERVICES';
export const TASKS_SERVICES = 'TASKS_SERVICES';
